### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [marcanuy/hugotube#1]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37678620-9da70f1a-2c8f-11e8-8c3f-0472a5d3b2a4.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by marcanuy** [comment]
Hi @paskal , thanks for reporting this. Now images use full width by default: 
![issue1-maxwidth](https://user-images.githubusercontent.com/954673/37688003-a6f38606-2c7c-11e8-8616-8d5f4896ac15.png)
